export type MurakamiBook = {
  title: string;
  originalTitle: string;
  year: string;
  type: "长篇小说" | "中篇小说";
  cover: string;
  summary: string;
  background: string;
  themes: readonly string[];
  structure: string;
  recommendation: string;
  personalNote: string;
  favorite?: boolean;
};

const openLibraryCover = (isbn: string) =>
  `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;

export const murakamiBooks: readonly MurakamiBook[] = [
  {
    title: "且听风吟",
    originalTitle: "風の歌を聴け",
    year: "1979",
    type: "中篇小说",
    cover: openLibraryCover("9780099590422"),
    summary: "二十一岁的“我”在海边小城度过暑假，与朋友鼠、酒吧老板杰和一位女孩相遇。",
    background: "村上春树的第一部小说，也是“青春三部曲”的起点。轻盈、疏离的叙述已经显露出后来作品中的音乐、酒吧与孤独。",
    themes: ["青春", "记忆", "孤独"],
    structure: "由短小片段、回忆和对话组成，像一张被夏日空气吹散的私人剪贴簿。",
    recommendation: "篇幅短、气质鲜明，适合想先感受早期村上语言节奏的读者。",
    personalNote: "故事看似什么也没有发生，却把一段无法重来的夏天保存得很完整。",
  },
  {
    title: "1973年的弹子球",
    originalTitle: "1973年のピンボール",
    year: "1980",
    type: "中篇小说",
    cover: openLibraryCover("9780099590422"),
    summary: "“我”寻找一台已经消失的弹子球机，鼠则在故乡面对无法言明的停滞。",
    background: "“青春三部曲”第二部。寻找弹子球机的行动逐渐成为对旧日生活与失落之物的追索。",
    themes: ["寻找", "失落", "告别"],
    structure: "两条生活线平行展开，以物件和回忆建立若即若离的联系。",
    recommendation: "如果喜欢安静、略带荒诞的寻找故事，可以从这里继续进入早期村上。",
    personalNote: "有些寻找并不是为了重新拥有，而是为了认真地说一次再见。",
  },
  {
    title: "寻羊冒险记",
    originalTitle: "羊をめぐる冒険",
    year: "1982",
    type: "长篇小说",
    cover: openLibraryCover("9780375718946"),
    summary: "一张照片中的神秘绵羊，把“我”带离东京，前往北海道寻找朋友鼠的踪迹。",
    background: "“青春三部曲”的终章，也被视为村上第一次真正展开完整长篇世界的作品。",
    themes: ["权力", "寻找", "自我"],
    structure: "从都市日常出发，逐步进入公路故事、谜案与超现实寓言。",
    recommendation: "适合喜欢冒险线索，又希望故事保留哲思和神秘感的读者。",
    personalNote: "从熟悉世界走向陌生之地的过程，也是人物第一次真正面对自己。",
  },
  {
    title: "世界尽头与冷酷仙境",
    originalTitle: "世界の終りとハードボイルド・ワンダーランド",
    year: "1985",
    type: "长篇小说",
    cover: openLibraryCover("9780679743460"),
    summary: "“冷酷仙境”的计算士与“世界尽头”的梦读者，在两个世界中同时逼近同一个答案。",
    background: "现实都市与封闭小镇交替叙述，以科幻、寓言和意识探索构成村上最独特的双重世界之一。",
    themes: ["意识", "现实与理想", "选择"],
    structure: "奇数章与偶数章分别讲述两个世界，直到它们在结尾互相照见。",
    recommendation: "喜欢双线结构、世界观和哲学意味的读者，可以把它作为进入村上异世界的第一本。",
    personalNote: "我最喜欢的作品之一。它让我开始思考：外部世界再复杂，内心仍能否保存一个愿意留下的地方。",
    favorite: true,
  },
  {
    title: "挪威的森林",
    originalTitle: "ノルウェイの森",
    year: "1987",
    type: "长篇小说",
    cover: openLibraryCover("9780375704024"),
    summary: "渡边在青春、爱情与死亡之间成长，并在直子和绿子代表的不同方向中寻找自己的生活。",
    background: "村上最广为人知的现实主义长篇，书名来自 The Beatles 的同名歌曲。",
    themes: ["青春", "爱情", "死亡"],
    structure: "由成年后的记忆展开，以第一人称回望六十年代末的青春经历。",
    recommendation: "想从情感和青春故事认识村上的读者，通常可以从这一本开始。",
    personalNote: "它不是一部简单的爱情小说，而是一段学习如何带着失去继续生活的过程。",
  },
  {
    title: "舞！舞！舞！",
    originalTitle: "ダンス・ダンス・ダンス",
    year: "1988",
    type: "长篇小说",
    cover: openLibraryCover("9780679753797"),
    summary: "“我”重返海豚宾馆寻找失踪的喜喜，在城市、梦境和人与人的联系中继续前行。",
    background: "承接《寻羊冒险记》的世界，却把问题转向高度消费化的现代都市和人与社会的连接。",
    themes: ["连接", "都市", "继续生活"],
    structure: "侦探式寻找与超现实空间交织，节奏像音乐一样不断推动人物向前。",
    recommendation: "如果喜欢城市、音乐、神秘感与较强故事性，这本很适合作为第一部长篇。",
    personalNote: "我最喜欢的作品之一。‘只要音乐还在响，就继续跳下去’像是一种不夸张、却坚定的生活方法。",
    favorite: true,
  },
  {
    title: "国境以南 太阳以西",
    originalTitle: "国境の南、太陽の西",
    year: "1992",
    type: "长篇小说",
    cover: openLibraryCover("9780679767398"),
    summary: "拥有家庭与爵士酒吧的始，重新遇到童年好友岛本，并开始动摇现有生活。",
    background: "一部体量克制的成人情感小说，讨论记忆中的可能人生如何进入现实。",
    themes: ["欲望", "选择", "另一种人生"],
    structure: "线性叙事为主，以童年回忆和成年重逢形成强烈对照。",
    recommendation: "适合想读较短、成熟而现实的村上爱情故事的读者。",
    personalNote: "真正危险的往往不是失去，而是把想象中的人生误认为唯一的答案。",
  },
  {
    title: "奇鸟行状录",
    originalTitle: "ねじまき鳥クロニクル",
    year: "1994",
    type: "长篇小说",
    cover: openLibraryCover("9780679775430"),
    summary: "冈田亨从寻找失踪的猫和妻子开始，逐渐进入家族秘密、战争记忆与意识深处。",
    background: "村上规模最庞大的作品之一，把私人生活的裂缝连接到二十世纪历史的暴力。",
    themes: ["历史", "暴力", "内在世界"],
    structure: "多位人物讲述各自经历，现实、梦境、档案和战争记忆层层嵌套。",
    recommendation: "读过一两本村上后再进入，会更容易享受它漫长而复杂的展开。",
    personalNote: "一个人向内挖掘得足够深时，也可能触碰到时代留下的黑暗。",
  },
  {
    title: "斯普特尼克恋人",
    originalTitle: "スプートニクの恋人",
    year: "1999",
    type: "长篇小说",
    cover: openLibraryCover("9780375726057"),
    summary: "“我”爱着堇，堇爱着敏；一次希腊旅行后，堇从现实中神秘消失。",
    background: "以第一颗人造卫星为意象，描写相互靠近却始终运行在不同轨道上的人。",
    themes: ["爱", "孤独", "平行世界"],
    structure: "由“我”的讲述、堇的文字与失踪谜团共同组成。",
    recommendation: "适合喜欢克制爱情、海岛氛围和开放式神秘结局的读者。",
    personalNote: "人与人可能离得很近，却仍隔着无法跨越的真空；珍贵的是我们依旧尝试呼唤。",
  },
  {
    title: "海边的卡夫卡",
    originalTitle: "海辺のカフカ",
    year: "2002",
    type: "长篇小说",
    cover: openLibraryCover("9781400079278"),
    summary: "十五岁的田村卡夫卡离家远行，会与猫交谈的中田则踏上另一条道路。",
    background: "借俄狄浦斯神话、图书馆、音乐和森林，讲述少年穿越命运阴影的成长。",
    themes: ["命运", "成长", "异世界"],
    structure: "两条人物线交替推进，因事件和象征逐渐靠近，但不以普通方式相遇。",
    recommendation: "故事性和奇幻感都很强，是进入村上大型长篇的理想入口。",
    personalNote: "世界会留下谜团，但人仍能穿过森林，带着无法完全解释的经历重新出发。",
  },
  {
    title: "天黑以后",
    originalTitle: "アフターダーク",
    year: "2004",
    type: "长篇小说",
    cover: openLibraryCover("9780307278739"),
    summary: "从午夜到清晨，东京夜色中的陌生人短暂相遇，沉睡的爱丽则身处另一个房间。",
    background: "一部发生在单个夜晚的城市小说，像镜头一样观察深夜仍未入睡的人。",
    themes: ["夜晚", "城市", "偶然相遇"],
    structure: "以时间刻度推进，叙述视角具有电影摄影机般的观察感。",
    recommendation: "篇幅不长、结构清晰，很适合喜欢都市夜景和电影感的读者。",
    personalNote: "白天互不相识的人，在夜晚短暂地成为彼此生活中的光。",
  },
  {
    title: "1Q84",
    originalTitle: "1Q84",
    year: "2009",
    type: "长篇小说",
    cover: openLibraryCover("9780307593313"),
    summary: "青豆与天吾进入悬挂着两个月亮的世界，在小小人、空气蛹与命运追捕中寻找彼此。",
    background: "村上篇幅最长的小说之一，以乔治·奥威尔《1984》为远方回声，建构出完整的平行现实。",
    themes: ["爱", "信念", "平行现实"],
    structure: "多位主角章节交替，时间与线索逐渐收束为一场漫长的相互寻找。",
    recommendation: "适合已经喜欢村上叙事，并准备进入一个可长期停留的庞大世界的读者。",
    personalNote: "两个月亮提醒我们：世界可能悄悄改变，而确认彼此仍然是辨认现实的方法。",
  },
  {
    title: "没有色彩的多崎作和他的巡礼之年",
    originalTitle: "色彩を持たない多崎つくると、彼の巡礼の年",
    year: "2013",
    type: "长篇小说",
    cover: openLibraryCover("9780385352109"),
    summary: "多崎作在多年后重新拜访四位旧友，寻找自己当年被突然排斥的原因。",
    background: "以李斯特《巡礼之年》为音乐线索，讨论创伤、友谊和重新理解过去。",
    themes: ["创伤", "友谊", "和解"],
    structure: "现实中的拜访与过去记忆交替，像一次逐站展开的内心巡礼。",
    recommendation: "叙事直接、悬念明确，适合想读当代都市与心理成长主题的读者。",
    personalNote: "过去无法改写，但可以被重新看见；理解并不等于忘记，却能让人继续前行。",
  },
  {
    title: "刺杀骑士团长",
    originalTitle: "騎士団長殺し",
    year: "2017",
    type: "长篇小说",
    cover: openLibraryCover("9780525520047"),
    summary: "离婚后的肖像画家住进山中画室，一幅隐藏的画和深夜铃声打开了观念世界。",
    background: "围绕绘画、创作和失去展开，也延续了村上关于地下空间与另一个世界的想象。",
    themes: ["艺术", "失去", "观念"],
    structure: "现实生活、神秘事件与象征世界逐步交叠，形成一段漫长的精神探险。",
    recommendation: "适合喜欢艺术主题、慢节奏展开和村上式异世界的读者。",
    personalNote: "创作不仅描绘眼前之物，也可能把未被说出的东西带回现实。",
  },
  {
    title: "城市与其不确定的墙",
    originalTitle: "街とその不確かな壁",
    year: "2023",
    type: "长篇小说",
    cover: openLibraryCover("9780593801970"),
    summary: "一座有高墙、影子和梦读者的城市再次出现，现实中的“我”则来到一间山中图书馆。",
    background: "村上在多年后重新展开早期构想，与《世界尽头与冷酷仙境》形成既熟悉又不同的回声。",
    themes: ["墙", "图书馆", "现实边界"],
    structure: "不同人生阶段与两种世界彼此映照，追问该留在何处、又该如何穿越墙。",
    recommendation: "更适合作为读过《世界尽头与冷酷仙境》之后的一次回返。",
    personalNote: "同一个意象在人生不同阶段会给出不同答案；墙也许既是阻隔，也是一种保护。",
  },
];

export const readingRoutes = [
  { label: "从青春与感情开始", book: "挪威的森林", note: "现实、克制，也最容易进入。" },
  { label: "从城市与寻找开始", book: "舞！舞！舞！", note: "音乐、旅馆、连接与继续生活。" },
  { label: "从双重世界开始", book: "世界尽头与冷酷仙境", note: "两条叙事通向同一个内心问题。" },
  { label: "从奇幻成长开始", book: "海边的卡夫卡", note: "命运、森林与离家少年的旅程。" },
] as const;
